export const dynamic = "force-dynamic";

import { createHandler } from "@/lib/api/handler";
import { getPrisma } from "@/lib/prisma";
import { createRateLimiter } from "@/lib/rate-limit";
import { pushFiles, createPullRequest } from "@/lib/github/client";
import { isValidGithubRepo, isValidGithubBranch } from "@/lib/sessions/validation";
import { NextResponse } from "next/server";
import type { IacFiles } from "@/components/session/CodePanel";

const exportLimiter = createRateLimiter("github-export", { maxRequests: 5, windowMs: 60_000 });

interface ExportRequestBody {
  sessionId?: unknown;
  repo?: unknown;
  branch?: unknown;
  createPr?: unknown;
  baseBranch?: unknown;
}

export const POST = createHandler<ExportRequestBody>(
  { rateLimit: exportLimiter },
  async ({ userId, body }) => {
    const { sessionId, repo, branch, createPr, baseBranch } = body;

    if (typeof sessionId !== "string" || sessionId.length === 0) {
      return NextResponse.json({ error: "sessionId is required" }, { status: 400 });
    }
    if (typeof repo !== "string" || !isValidGithubRepo(repo)) {
      return NextResponse.json({ error: "repo must be a valid owner/repo string" }, { status: 400 });
    }
    if (typeof branch !== "string" || !isValidGithubBranch(branch)) {
      return NextResponse.json({ error: "branch is required and must be a valid branch name" }, { status: 400 });
    }
    if (createPr !== undefined && typeof createPr !== "boolean") {
      return NextResponse.json({ error: "createPr must be a boolean" }, { status: 400 });
    }
    if (createPr && (typeof baseBranch !== "string" || !isValidGithubBranch(baseBranch))) {
      return NextResponse.json({ error: "baseBranch is required when createPr is true" }, { status: 400 });
    }

    const session = await getPrisma().session.findUnique({ where: { id: sessionId } });
    if (!session || session.userId !== userId) {
      return NextResponse.json({ error: "Session not found" }, { status: 404 });
    }
    if (!session.iacCode) {
      return NextResponse.json({ error: "No code generated yet" }, { status: 400 });
    }
    if (session.iacStale) {
      return NextResponse.json(
        { error: "Code is outdated — regenerate before exporting" },
        { status: 409 },
      );
    }

    const iacFiles = session.iacCode as unknown as IacFiles;
    const pushResult = await pushFiles({
      repo,
      branch,
      message: `Update Terraform via Conjure (session: ${session.name})`,
      files: [
        { path: "main.tf", content: iacFiles.mainTf },
        { path: "variables.tf", content: iacFiles.variablesTf },
        { path: "outputs.tf", content: iacFiles.outputsTf },
      ],
    });

    if ("error" in pushResult) {
      return NextResponse.json({ error: pushResult.error }, { status: 502 });
    }

    if (!createPr) {
      return NextResponse.json({ sha: pushResult.sha });
    }

    const prResult = await createPullRequest({
      repo,
      title: `Terraform infrastructure update from Conjure`,
      body: `This PR was generated by [Conjure](https://conjure.app) from session **${session.name}**.\n\nContains Terraform HCL for ${session.targetEnv.toUpperCase()} infrastructure.`,
      head: branch,
      base: baseBranch as string,
    });

    if ("error" in prResult) {
      // Push succeeded but PR creation failed — return partial success with sha
      return NextResponse.json({ sha: pushResult.sha, prError: prResult.error }, { status: 207 });
    }

    return NextResponse.json({ sha: pushResult.sha, prUrl: prResult.url });
  },
);
